### ISSUE TITLE
Input size

### ISSUE THREAD

**Issue by lvoegtlin** [zhiqwang/image-captioning#15]
Is it possible to train the network with images of different size?

**Comment by zhiqwang** [comment]
Refer to issue #7 and issue #11

**Comment by lvoegtlin** [comment]
thanks for the fast answer. Did not see these issues.
When I use the ```--keep-ratio``` the network crashes in the ```best_path_decode()``` method with this message:
```Traceback (most recent call last):
  File "/home/staff/voegtlil/crnn.pytorch/main.py", line 433, in <module>
    main()
  File "/home/staff/voegtlil/crnn.pytorch/main.py", line 215, in main
    _ = train(train_loader, model, criterion, optimizer, epoch, converter, writer)
  File "/home/staff/voegtlil/crnn.pytorch/main.py", line 276, in train
    preds.append(converter.best_path_decode(log_prob, strings=False)[0])
  File "/home/staff/voegtlil/crnn.pytorch/utils/converter.py", line 94, in best_path_decode
    _, probs = probs.max(2)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)```

The input files have different dimensions and also a different amount of characters on them.
